### ISSUE TITLE
Get Battery Level From Scanner

### ISSUE THREAD

**Issue by benkirbycodes** [SocketMobile/capturebasic-cordova-ios#3]
My team needs to be able to get the scanner's battery level with this plugin. Is there any plan to build out the `getProperty` method that's currently commented out (which I assume would be used to get details about the scanner)?
```
// exports.getProperty = function(arg0, success, error) {
//   exec(success, error, 'CaptureBasicCordova', 'getProperty', [arg0]);
// };
```

**Comment by benkirbycodes** [comment]
Just checking back in on this. Any possibility of getting this built out?

**Comment by EricGlaenzer** [comment]
Hi @benkirbycodes, sorry for my late reply. 
I will give an update to this by 1/23. We don't have any plan for Cordova at the moment, but if that is something fairly simple then maybe we can squeeze this feature in our roadmap.

**Comment by benkirbycodes** [comment]
Thanks @EricGlaenzer. If you could squeeze it in, that would help us out a lot.

**Comment by EricGlaenzer** [comment]
@benkirbycodes quick update, I am in the process of adding the getProperty, and testing it with the battery level. I am still testing this feature. I'll provide a quick status tomorrow.

**Comment by benkirbycodes** [comment]
@EricGlaenzer That's great to hear, thanks so much!

**Comment by EricGlaenzer** [comment]
@benkirbycodes The Get/Set property feature has been added. There is a very simple example in the README to show how to get the battery level of a device. I did a minimal testing with a S720.
