### ISSUE TITLE
Scanner Lag After Certain Number Of Scans

### ISSUE THREAD

**Issue by benkirbycodes** [SocketMobile/capturebasic-cordova-ios#4]
Hey @EricGlaenzer, hope everything is going ok for you. This is a bit of a shot in the dark, but we've encountered an issue that we're hoping you may know something about.

When using `capturebasic-cordova-ios` with our Ionic 6 application, everything works great until the number of consecutive scans reaches ~230 (the number seems to vary a little depending on circumstances, but is usually close to this). After that, the lag time between the scan occurring on the scanner and the SDK acknowledging it suddenly becomes several seconds. This lag continues until the app is restarted.

We've scoured our code pretty thoroughly and are reasonably sure it's not something we're causing ourselves. Another thing to note is that for Android devices, we're using `socketmobile-capturejs` and do not experience this. 

Any insight or recommendations you could give would be greatly appreciated because we're pretty stumped.

**Comment by EricGlaenzer** [comment]
Hi @benkirbycodes , thank you for sharing this issue. Can you share the various version of your environment? iPadOs or iOS? CaptureSDK version? Ionic version? We could try to reproduce this issue but that will help to know more about your environment.

**Comment by benkirbycodes** [comment]
Yeah, I can definitely do that. 

iOS: 16.6.1
capturebasiccordova: 0.3.0
CaptureSDK: 1.8.34
Ionic: 6
Capacitor: 4

Thanks

**Comment by benkirbycodes** [comment]
Hi @EricGlaenzer. Just circling back here to see if you had any luck reproducing this issue?

Thanks!

**Comment by EricGlaenzer** [comment]
Hi @benkirbycodes , not yet, it's on my list and I should be able to get to it by Friday. I will let you know by then. 
Thanks

**Comment by benkirbycodes** [comment]
Thanks @EricGlaenzer !

**Comment by benkirbycodes** [comment]
Hey @EricGlaenzer, just checking in on this. Any luck?

**Comment by EricGlaenzer** [comment]
Hi @benkirbycodes I am still working on it today... few minor issues about my setup here, since a few things have been updated since the last release... I will provide an update by the end of today.

**Comment by benkirbycodes** [comment]
Thanks @EricGlaenzer, I appreciate it.

**Comment by EricGlaenzer** [comment]
Hi @benkirbycodes 
I did a comparaison with the same Cordova app, older version of the SDK and latest version of the SDK, and it is slightly better than the older SDK, and over 200 scans without any increase in time while scanning.
[comparaison - scans over time.pdf](https://github.com/SocketMobile/capturebasic-cordova-ios/files/13343765/comparaison.-.scans.over.time.pdf)

**Comment by benkirbycodes** [comment]
Ok, thanks @EricGlaenzer.
